
on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Printing folder contents'
        run: pwd


    

      - name: 'testing printing'
        run: echo Mohamed